"""Configuration GUI for the Odoo Attendance automation.

Professional desktop application layout:
  - Frameless window with custom title bar (minimize/close, draggable)
  - Left sidebar navigation
  - Clean forms with labels above inputs
  - Clear footer with primary/secondary/contextual actions
  - Auto light/dark theme
"""

from __future__ import annotations

import os
import subprocess
import sys
import threading
from datetime import date, datetime as dt
from pathlib import Path
from tkinter import (
    BOTH, END, LEFT, RIGHT, X, Y, BOTTOM, TOP,
    StringVar, BooleanVar, messagebox, scrolledtext, ttk,
)
import tkinter as tk

try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib  # type: ignore[no-redef]

SCRIPT_DIR = Path(__file__).resolve().parent
CONFIG_PATH = SCRIPT_DIR / "config.toml"
EXAMPLE_PATH = SCRIPT_DIR / "config.example.toml"
ATTENDANCE_SCRIPT = SCRIPT_DIR / "odoo_attendance.py"
PYTHON_EXE = Path(sys.executable)

from version import get_version
APP_VERSION = get_version()

from theme import get_theme, fonts, apply_ttk_theme, detect_dark_mode
from datepickers import DateEntry, TimeEntry
from widgets import ModernEntry, ModernButton, ModernScrollbar, ModernCheck, ModernToggle

WEEKDAYS_ES = ["Lun", "Mar", "Mie", "Jue", "Vie", "Sab", "Dom"]
WEEKDAYS_FULL = ["Lunes", "Martes", "Miercoles", "Jueves",
                 "Viernes", "Sabado", "Domingo"]

NAV_ITEMS = [
    ("general", "General"),
    ("normal", "Horario normal"),
    ("summer", "Horario verano"),
    ("special", "Dias especiales"),
    ("bulk", "Fichaje en masa"),
]


def _no_console_si():
    if os.name == "nt":
        si = subprocess.STARTUPINFO()  # type: ignore[attr-defined]
        si.dwFlags |= subprocess.STARTF_USESHOWWINDOW  # type: ignore[attr-defined]
        si.wShowWindow = subprocess.SW_HIDE  # type: ignore[attr-defined]
        return si
    return None


# ── Config load / save ────────────────────────────────────────────────────
def default_config() -> dict:
    return {
        "odoo": {
            "url": "https://demo.odoo.com/odoo",
            "username": "demo@ejemplo.com",
            "password": "CAMBIAR_ESTA_CONTRASENA",
            "headless": False,
            "user_data_dir": "",
        },
        "behavior": {"enabled": True, "skip_weekdays": [5, 6], "check_updates": True},
        "schedule": {
            "summer_months": [7, 8],
            "summer": {str(i): [] for i in range(7)},
            "normal": {str(i): [] for i in range(7)},
            "special_days": {},
        },
    }


def load_config() -> dict:
    path = CONFIG_PATH if CONFIG_PATH.exists() else EXAMPLE_PATH
    if path.exists():
        with open(path, "rb") as fh:
            cfg = tomllib.load(fh)
        base = default_config()
        base["odoo"].update(cfg.get("odoo", {}))
        base["behavior"].update(cfg.get("behavior", {}))
        sched = cfg.get("schedule", {})
        base["schedule"]["summer_months"] = sched.get("summer_months", [7, 8])
        for kind in ("summer", "normal"):
            base["schedule"][kind] = {
                str(i): [tuple(b) for b in sched.get(kind, {}).get(str(i), [])]
                for i in range(7)
            }
        base["schedule"]["special_days"] = {
            k: [tuple(b) for b in v]
            for k, v in sched.get("special_days", {}).items()
        }
        return base
    return default_config()


def _fmt_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def save_config(cfg: dict) -> None:
    odoo = cfg["odoo"]
    beh = cfg["behavior"]
    sched = cfg["schedule"]

    def block_str(blocks: list) -> str:
        if not blocks:
            return "[]"
        return "[" + ", ".join(
            f"[{_fmt_str(b[0])}, {_fmt_str(b[1])}, {_fmt_str(b[2])}]" for b in blocks
        ) + "]"

    lines = [
        "# Odoo Attendance - Configuration (generated by config_gui.py)",
        "",
        "[odoo]",
        f"url = {_fmt_str(str(odoo.get('url', '')))}",
        f"username = {_fmt_str(str(odoo.get('username', '')))}",
        f"password = {_fmt_str(str(odoo.get('password', '')))}",
        f"headless = {str(bool(odoo.get('headless', False))).lower()}",
        f"user_data_dir = {_fmt_str(str(odoo.get('user_data_dir', '')))}",
        "",
        "[behavior]",
        f"enabled = {str(bool(beh.get('enabled', True))).lower()}",
        f"skip_weekdays = [{', '.join(str(int(x)) for x in beh.get('skip_weekdays', []))}]",
        "",
        "[schedule]",
        f"summer_months = [{', '.join(str(int(x)) for x in sched.get('summer_months', []))}]",
    ]
    for kind, label in (("summer", "summer / intensive"), ("normal", "normal")):
        lines += ["", f"# {label} schedule  (0=Monday ... 6=Sunday)",
                  f"[schedule.{kind}]"]
        for i in range(7):
            lines.append(f"{i} = {block_str(sched.get(kind, {}).get(str(i), []))}")
    lines += ["", '# Special days  (key = "MM-DD")',
              "[schedule.special_days]"]
    sd = sched.get("special_days", {})
    if sd:
        for k in sorted(sd.keys()):
            lines.append(f'{_fmt_str(k)} = {block_str(sd[k])}')
    else:
        lines.append("# (none)")
    lines.append("")
    CONFIG_PATH.write_text("\n".join(lines), encoding="utf-8")


# ── Block editor ──────────────────────────────────────────────────────────
class DayEditor(ttk.Frame):
    """Editor for a single weekday's time blocks."""

    def __init__(self, master, weekday_name: str, blocks: list,
                 on_change, C, F):
        super().__init__(master, style="Surface.TFrame")
        self.C = C
        self.F = F
        self._on_change = on_change
        self._rows = []

        if weekday_name:
            ttk.Label(self, text=weekday_name, font=F["body_b"],
                      style="Surface.TLabel").pack(anchor="w", pady=(0, 6))

        self._table = ttk.Frame(self, style="Surface.TFrame")
        self._table.pack(fill=X)

        for c, txt in enumerate(["Entrada", "Salida", "Categoria"]):
            ttk.Label(self._table, text=txt, font=F["small"],
                      foreground=C["text_sec"],
                      style="Surface.TLabel").grid(
                row=0, column=c, padx=(0, 12), sticky="w")

        for b in blocks:
            self._add_row(b)

        ModernButton(self, "+ Anadir bloque", C, F,
                     command=lambda: self._add_row(["09:00", "14:00", "Trabajo"]),
                     padx=12, pady=6).pack(anchor="w", pady=(8, 0))

    def _add_row(self, block) -> None:
        r = len(self._rows) + 1
        in_var = StringVar(value=block[0])
        out_var = StringVar(value=block[1])
        cat_var = StringVar(value=block[2])
        e1 = TimeEntry(self._table, in_var, self.C, self.F, width=7)
        e2 = TimeEntry(self._table, out_var, self.C, self.F, width=7)
        e3 = ModernEntry(self._table, self.C, self.F, textvariable=cat_var,
                         width=16)
        for w, var, col in ((e1, in_var, 0), (e2, out_var, 1), (e3, cat_var, 2)):
            w.grid(row=r, column=col, padx=(0, 12), pady=3)
            var.trace_add("write", lambda *_: self._on_change())
        del_btn = tk.Button(
            self._table, text="\u2715", width=3,
            relief="flat", bd=0,
            bg=self.C["surface2"], fg=self.C["text_sec"],
            activebackground=self.C["surface3"],
            font=self.F["small"],
            highlightthickness=0,
            command=lambda: self._del_row(r))
        del_btn.grid(row=r, column=3, padx=0)
        self._rows.append([e1, e2, e3, del_btn, in_var, out_var, cat_var])

    def _del_row(self, row_idx: int) -> None:
        for i, row in enumerate(self._rows):
            if row[3].grid_info().get("row") == row_idx:
                for w in row[:4]:
                    if w:
                        w.destroy()
                self._rows.pop(i)
                self._on_change()
                return

    def get_blocks(self) -> list[list[str]]:
        result = []
        for row in self._rows:
            cin = row[4].get().strip()
            cout = row[5].get().strip()
            cat = row[6].get().strip()
            if cin or cout or cat:
                result.append([cin, cout, cat])
        return result


# ── Main application ──────────────────────────────────────────────────────
class ConfigApp:
    SIDEBAR_W = 200
    TITLEBAR_H = 38

    def __init__(self) -> None:
        self.cfg = load_config()
        self._dark = detect_dark_mode()
        self.C = get_theme(self._dark)
        self.F = fonts()

        self.root = tk.Tk()
        self.root.title(f"Odoo Attendance  \u2014  v{APP_VERSION}")
        self.root.geometry("820x640")
        self.root.configure(bg=self.C["bg"])
        self._dirty = False
        self._canvases: list[tk.Canvas] = []
        self._current_nav = "general"

        self._style = ttk.Style()
        apply_ttk_theme(self._style, self.C)

        # Frameless window: we draw our own title bar
        self.root.overrideredirect(True)
        self.root.update_idletasks()
        sw = self.root.winfo_screenwidth()
        sh = self.root.winfo_screenheight()
        self.root.geometry(f"+{(sw - 820) // 2}+{(sh - 640) // 2}")

        self._build_ui()
        self.root.bind_all("<MouseWheel>", self._on_mousewheel)
        self.root.protocol("WM_DELETE_WINDOW", self._on_close)
        self.root.after(50, self._ensure_taskbar)

        if self.cfg.get("behavior", {}).get("check_updates", True):
            self.root.after(1500, self._check_updates_bg)

    # ── Frameless window helpers ──────────────────────────────────────────
    def _ensure_taskbar(self) -> None:
        """Keep the frameless window in the taskbar on Windows."""
        if os.name != "nt":
            return
        try:
            import ctypes
            hwnd = ctypes.windll.user32.GetParent(self.root.winfo_id())
            GWL_EXSTYLE = -20
            WS_EX_APPWINDOW = 0x00040000
            style = ctypes.windll.user32.GetWindowLongW(hwnd, GWL_EXSTYLE)
            ctypes.windll.user32.SetWindowLongW(
                hwnd, GWL_EXSTYLE, style | WS_EX_APPWINDOW)
        except Exception:
            pass

    def _minimize(self) -> None:
        if os.name == "nt":
            try:
                import ctypes
                hwnd = ctypes.windll.user32.GetParent(self.root.winfo_id())
                ctypes.windll.user32.ShowWindow(hwnd, 6)  # SW_MINIMIZE
                return
            except Exception:
                pass
        self.root.iconify()

    def _start_drag(self, e) -> None:
        self._drag_x = e.x_root - self.root.winfo_x()
        self._drag_y = e.y_root - self.root.winfo_y()

    def _do_drag(self, e) -> None:
        self.root.geometry(f"+{e.x_root - self._drag_x}+{e.y_root - self._drag_y}")

    # ── Layout ────────────────────────────────────────────────────────────
    def _make_title_button(self, titlebar, text: str, hover_bg, hover_fg,
                           command) -> tk.Button:
        """Title bar button with proper hover feedback."""
        C = self.C
        btn = tk.Button(
            titlebar, text=text, width=4,
            relief="flat", bd=0,
            bg=C["title_bg"], fg=C["text_sec"],
            activebackground=hover_bg, activeforeground=hover_fg,
            font=("Segoe UI", 10) if os.name == "nt" else ("Sans", 10),
            highlightthickness=0, command=command, cursor="hand2")

        def _enter(_e):
            btn.configure(bg=hover_bg, fg=hover_fg)

        def _leave(_e):
            btn.configure(bg=C["title_bg"], fg=C["text_sec"])

        btn.bind("<Enter>", _enter)
        btn.bind("<Leave>", _leave)
        return btn

    def _build_ui(self) -> None:
        C = self.C

        # ── Custom title bar ──
        titlebar = tk.Frame(self.root, bg=C["title_bg"], height=self.TITLEBAR_H)
        titlebar.pack(fill=X, side=TOP)
        titlebar.pack_propagate(False)

        tk.Label(titlebar, text="Odoo Attendance",
                 bg=C["title_bg"], fg=C["text"],
                 font=("Segoe UI", 10, "bold") if os.name == "nt"
                 else ("Sans", 10, "bold")).pack(side=LEFT, padx=(14, 6))
        tk.Label(titlebar, text=f"v{APP_VERSION}",
                 bg=C["title_bg"], fg=C["text_dis"],
                 font=("Segoe UI", 9) if os.name == "nt" else ("Sans", 9)).pack(
            side=LEFT)

        btn_close = self._make_title_button(
            titlebar, "\u2715", C["error"], "#ffffff", self._on_close)
        btn_close.pack(side=RIGHT, fill=Y)
        btn_min = self._make_title_button(
            titlebar, "\u2013", C["surface4"], C["text"], self._minimize)
        btn_min.pack(side=RIGHT, fill=Y)

        # Drag anywhere on the title bar
        titlebar.bind("<Button-1>", self._start_drag)
        titlebar.bind("<B1-Motion>", self._do_drag)

        # ── Footer (packed BEFORE main so it reserves bottom space) ──
        footer = tk.Frame(self.root, bg=C["footer_bg"], height=64)
        footer.pack(side=BOTTOM, fill=X)
        footer.pack_propagate(False)
        tk.Frame(footer, bg=C["border"], height=1).pack(fill=X, side=TOP)

        footer_inner = tk.Frame(footer, bg=C["footer_bg"])
        footer_inner.pack(fill=X, padx=24, pady=14)

        ModernButton(footer_inner, "Fichar ahora", C, self.F,
                     command=self._fichar_ahora).pack(side=LEFT)
        ModernButton(footer_inner, "Cancelar", C, self.F,
                     command=self._on_close).pack(side=RIGHT, padx=(8, 0))
        ModernButton(footer_inner, "Guardar", C, self.F,
                     variant="primary", command=self._save).pack(side=RIGHT)

        # ── Main container (fills remaining space) ──
        main = ttk.Frame(self.root, style="TFrame")
        main.pack(fill=BOTH, expand=True)

        # ── Sidebar ──
        sidebar = tk.Frame(main, bg=C["nav_bg"], width=self.SIDEBAR_W)
        sidebar.pack(side=LEFT, fill=Y)
        sidebar.pack_propagate(False)

        # Nav items
        self._nav_buttons: dict[str, tk.Frame] = {}
        self._nav_labels: dict[str, tk.Label] = {}
        self._nav_indicators: dict[str, tk.Frame] = {}

        for key, label in NAV_ITEMS:
            item = tk.Frame(sidebar, bg=C["nav_bg"], height=40)
            item.pack(fill=X)
            item.pack_propagate(False)

            indicator = tk.Frame(item, bg=C["nav_bg"], width=3)
            indicator.pack(side=LEFT, fill=Y)

            lbl = tk.Label(item, text=label, bg=C["nav_bg"],
                           fg=C["text_sec"], font=self.F["nav"],
                           anchor="w", padx=20)
            lbl.pack(side=LEFT, fill=X, expand=True, pady=8)

            def _enter(e, k=key):
                self._nav_hover(k, True)

            def _leave(e, k=key):
                self._nav_hover(k, False)

            def _click(e, k=key):
                self._show_page(k)

            item.bind("<Enter>", _enter)
            item.bind("<Leave>", _leave)
            item.bind("<Button-1>", _click)
            lbl.bind("<Enter>", _enter)
            lbl.bind("<Leave>", _leave)
            lbl.bind("<Button-1>", _click)

            self._nav_buttons[key] = item
            self._nav_labels[key] = lbl
            self._nav_indicators[key] = indicator

        # ── Content area ──
        self._content_area = tk.Frame(main, bg=C["surface"])
        self._content_area.pack(side=LEFT, fill=BOTH, expand=True)

        # Pages: container (for show/hide) + inner (for building content)
        self._pages: dict[str, tk.Frame] = {}
        self._page_inners: dict[str, ttk.Frame] = {}
        for key, _ in NAV_ITEMS:
            container, inner = self._make_scrollable_page(key)
            self._pages[key] = container
            self._page_inners[key] = inner

        self._build_general(self._page_inners["general"])
        self._build_schedule(self._page_inners["normal"], "normal")
        self._build_schedule(self._page_inners["summer"], "summer")
        self._build_special(self._page_inners["special"])
        self._build_bulk(self._page_inners["bulk"])

        self._show_page("general")

    def _nav_hover(self, key: str, enter: bool) -> None:
        C = self.C
        if key == self._current_nav:
            return
        bg = C["nav_hov"] if enter else C["nav_bg"]
        btn = self._nav_buttons[key]
        lbl = self._nav_labels[key]
        ind = self._nav_indicators[key]
        btn.configure(bg=bg)
        lbl.configure(bg=bg)
        ind.configure(bg=bg)

    def _make_scrollable_page(self, key: str) -> tuple[tk.Frame, ttk.Frame]:
        """Create a scrollable page.

        Returns (container, inner): the container is packed/unpacked to
        show/hide the page; the inner frame is where content is built.
        """
        C = self.C
        container = tk.Frame(self._content_area, bg=C["surface"])
        container.pack(fill=BOTH, expand=True)
        container.pack_forget()  # hidden until selected

        canvas = tk.Canvas(container, bg=C["surface"], borderwidth=0,
                           highlightthickness=0)
        scroll = ModernScrollbar(container, canvas.yview, C)
        inner = ttk.Frame(canvas, style="Surface.TFrame")
        inner.bind("<Configure>",
                   lambda e: canvas.configure(scrollregion=canvas.bbox("all")))
        win_id = canvas.create_window((0, 0), window=inner, anchor="nw")
        canvas.configure(yscrollcommand=scroll.set)
        # Pack scrollbar FIRST so canvas fills the remaining space
        scroll.pack(side=RIGHT, fill=Y)
        canvas.pack(side=LEFT, fill=BOTH, expand=True)
        self._canvases.append(canvas)

        def _on_resize(event):
            canvas.itemconfigure(win_id, width=event.width)
        canvas.bind("<Configure>", _on_resize)

        return container, inner

    def _show_page(self, key: str) -> None:
        C = self.C
        # Hide all page containers
        for page in self._pages.values():
            page.pack_forget()

        # Show selected
        self._pages[key].pack(fill=BOTH, expand=True)

        # Update nav styles
        for k, _ in NAV_ITEMS:
            is_active = (k == key)
            btn = self._nav_buttons[k]
            lbl = self._nav_labels[k]
            ind = self._nav_indicators[k]
            if is_active:
                btn.configure(bg=C["nav_active"])
                lbl.configure(bg=C["nav_active"], fg=C["text"],
                              font=self.F["nav_active"])
                ind.configure(bg=C["nav_indicator"])
            else:
                btn.configure(bg=C["nav_bg"])
                lbl.configure(bg=C["nav_bg"], fg=C["text_sec"],
                              font=self.F["nav"])
                ind.configure(bg=C["nav_bg"])

        self._current_nav = key

    def _on_mousewheel(self, event) -> None:
        for canvas in self._canvases:
            try:
                if canvas.winfo_ismapped():
                    canvas.yview_scroll(int(-1 * (event.delta / 120)), "units")
                    return
            except Exception:
                pass

    # ── Section helpers ───────────────────────────────────────────────────
    def _section_title(self, parent, title: str) -> None:
        C, F = self.C, self.F
        ttk.Label(parent, text=title, style="Surface.TLabel",
                  font=F["section"], foreground=C["text"]).pack(
            anchor="w", pady=(16, 4))
        tk.Frame(parent, bg=C["border"], height=1).pack(
            fill=X, pady=(0, 12))

    def _field(self, parent, label: str, var: StringVar, show: str = "",
               width: int = 48, helper: str = "") -> ModernEntry:
        C, F = self.C, self.F
        ttk.Label(parent, text=label, style="Surface.TLabel",
                  font=F["label"], foreground=C["text_sec"]).pack(
            anchor="w", pady=(10, 4))
        entry = ModernEntry(parent, C, F, textvariable=var, show=show,
                            width=width)
        entry.pack(anchor="w", fill=X if width >= 40 else None)
        if helper:
            ttk.Label(parent, text=helper, style="Surface.TLabel",
                      font=F["helper"], foreground=C["text_dis"]).pack(
                anchor="w", pady=(2, 0))
        var.trace_add("write", self._mark_dirty)
        return entry

    # ── General page ──────────────────────────────────────────────────────
    def _build_general(self, parent) -> None:
        C, F = self.C, self.F
        pad = ttk.Frame(parent, style="Surface.TFrame")
        pad.pack(fill=BOTH, expand=True, padx=32, pady=(8, 24))

        # ── Credenciales ──
        self._section_title(pad, "Credenciales Odoo")

        odoo = self.cfg["odoo"]
        self._url = StringVar(value=odoo.get("url", ""))
        self._user = StringVar(value=odoo.get("username", ""))
        self._pass = StringVar(value=odoo.get("password", ""))
        self._headless = BooleanVar(value=bool(odoo.get("headless", False)))
        self._udd = StringVar(value=odoo.get("user_data_dir", ""))

        self._field(pad, "URL Odoo", self._url)
        self._field(pad, "Usuario", self._user)
        self._field(pad, "Contrasena", self._pass, show="*")
        self._field(pad, "Perfil Chrome", self._udd, width=48,
                    helper="Opcional. Ruta al perfil de Chrome para reutilizar la sesion.")

        ModernCheck(pad, "Chrome en modo headless (sin ventana visible)",
                    self._headless, C, F,
                    command=self._mark_dirty).pack(anchor="w", pady=(14, 0))

        # ── Comportamiento ──
        self._section_title(pad, "Comportamiento")

        beh = self.cfg["behavior"]
        self._enabled = BooleanVar(value=bool(beh.get("enabled", True)))
        ModernCheck(pad, "Activar dialogo de fichaje al desbloquear el PC",
                    self._enabled, C, F,
                    command=self._mark_dirty).pack(anchor="w", pady=(0, 18))

        ttk.Label(pad, text="Dias en los que NO preguntar",
                  style="Surface.TLabel", font=F["label"],
                  foreground=C["text_sec"]).pack(anchor="w", pady=(0, 6))
        self._skip_vars = [
            BooleanVar(value=(i in beh.get("skip_weekdays", [])))
            for i in range(7)
        ]
        skip_frame = tk.Frame(pad, bg=C["surface"])
        skip_frame.pack(anchor="w", pady=(0, 18))
        for i, name in enumerate(WEEKDAYS_ES):
            ModernToggle(skip_frame, name, self._skip_vars[i], C, F,
                         on_change=self._mark_dirty).pack(
                side=LEFT, padx=(0, 4))

        ttk.Label(pad, text="Meses con horario de verano / intensivo",
                  style="Surface.TLabel", font=F["label"],
                  foreground=C["text_sec"]).pack(anchor="w", pady=(0, 4))
        self._summer_months = StringVar(
            value=", ".join(str(m) for m in self.cfg["schedule"].get("summer_months", [])))
        ModernEntry(pad, C, F, textvariable=self._summer_months,
                    width=30).pack(anchor="w")
        ttk.Label(pad, text="ej: 7, 8  \u2014  vacio = sin horario de verano",
                  style="Surface.TLabel", font=F["helper"],
                  foreground=C["text_dis"]).pack(anchor="w", pady=(2, 0))
        self._summer_months.trace_add("write", self._mark_dirty)

    # ── Schedule pages ────────────────────────────────────────────────────
    def _day_card(self, parent, title: str) -> tk.Frame:
        """Subtle bordered box that groups a weekday section."""
        C = self.C
        outer = tk.Frame(parent, bg=C["surface"],
                         highlightthickness=1,
                         highlightbackground=C["border"])
        outer.pack(fill=X, pady=(12, 0))
        header = tk.Frame(outer, bg=C["surface"])
        header.pack(fill=X, padx=16, pady=(10, 6))
        tk.Label(header, text=title, bg=C["surface"], fg=C["text"],
                 font=self.F["body_b"]).pack(side=LEFT)
        tk.Frame(outer, bg=C["border"], height=1).pack(fill=X, padx=16)
        body = tk.Frame(outer, bg=C["surface"])
        body.pack(fill=X, padx=16, pady=(8, 12))
        return body

    def _build_schedule(self, parent, kind: str) -> None:
        C, F = self.C, self.F
        pad = ttk.Frame(parent, style="Surface.TFrame")
        pad.pack(fill=BOTH, expand=True, padx=32, pady=(8, 24))

        self._day_editors: dict = getattr(self, "_day_editors", {})
        self._day_editors[kind] = {}
        days = self.cfg["schedule"].get(kind, {})

        for i in range(7):
            blocks = days.get(str(i), [])
            card = self._day_card(pad, WEEKDAYS_FULL[i])
            ed = DayEditor(card, "", blocks, self._mark_dirty, C, F)
            ed.pack(fill=X)
            self._day_editors[kind][str(i)] = ed

    # ── Special days page ─────────────────────────────────────────────────
    def _build_special(self, parent) -> None:
        C, F = self.C, self.F
        pad = ttk.Frame(parent, style="Surface.TFrame")
        pad.pack(fill=BOTH, expand=True, padx=32, pady=(8, 24))

        self._section_title(pad, "Dias especiales")

        add_frame = tk.Frame(pad, bg=C["surface"])
        add_frame.pack(fill=X, pady=(0, 16))
        ttk.Label(add_frame, text="Anadir dia (MM-DD):",
                  style="Surface.TLabel", font=F["label"],
                  foreground=C["text_sec"]).pack(side=LEFT)
        self._new_sd = StringVar(value="")
        ModernEntry(add_frame, C, F, textvariable=self._new_sd,
                    width=10).pack(side=LEFT, padx=(8, 8))
        ModernButton(add_frame, "Anadir", C, F,
                     command=self._add_special, padx=14, pady=6).pack(
            side=LEFT)

        self._special_editors: dict[str, DayEditor] = {}
        self._special_container = ttk.Frame(pad, style="Surface.TFrame")
        self._special_container.pack(fill=BOTH, expand=True)

        for k, blocks in self.cfg["schedule"].get("special_days", {}).items():
            self._add_special_editor(k, blocks)

    def _add_special(self) -> None:
        key = self._new_sd.get().strip()
        if not key:
            return
        try:
            mm, dd = key.split("-")
            key = f"{int(mm):02d}-{int(dd):02d}"
        except ValueError:
            messagebox.showerror("Error", "Formato invalido. Usa MM-DD (ej: 12-24).")
            return
        if key in self._special_editors:
            return
        self._add_special_editor(key, [["08:00", "12:00", "Trabajo"]])
        self._new_sd.set("")
        self._mark_dirty()

    def _add_special_editor(self, key: str, blocks: list) -> None:
        C, F = self.C, self.F
        wrapper = tk.Frame(self._special_container, bg=C["surface"],
                           highlightthickness=1,
                           highlightbackground=C["border"])
        wrapper.pack(fill=X, pady=(0, 16))

        top = tk.Frame(wrapper, bg=C["surface"])
        top.pack(fill=X, padx=16, pady=(10, 6))
        ttk.Label(top, text=f"Dia {key}", style="Surface.TLabel",
                  font=F["body_b"], foreground=C["text"]).pack(side=LEFT)
        tk.Button(top, text="Eliminar", relief="flat", bd=0,
                  bg=C["surface"], fg=C["error"],
                  activebackground=C["surface3"],
                  font=F["small"], highlightthickness=0,
                  command=lambda: self._del_special(key, wrapper)).pack(
            side=RIGHT)
        tk.Frame(wrapper, bg=C["border"], height=1).pack(fill=X, padx=16)

        body = tk.Frame(wrapper, bg=C["surface"])
        body.pack(fill=X, padx=16, pady=(8, 12))
        ed = DayEditor(body, "", blocks, self._mark_dirty, C, F)
        ed.pack(fill=X)
        self._special_editors[key] = ed

    def _del_special(self, key: str, frame) -> None:
        frame.destroy()
        self._special_editors.pop(key, None)
        self._mark_dirty()

    # ── Bulk page ─────────────────────────────────────────────────────────
    def _build_bulk(self, parent) -> None:
        C, F = self.C, self.F
        pad = ttk.Frame(parent, style="Surface.TFrame")
        pad.pack(fill=BOTH, expand=True, padx=32, pady=(8, 24))

        self._section_title(pad, "Fichaje por rango de fechas")

        ttk.Label(pad, text=(
            "Registra la asistencia de todos los dias laborables entre dos fechas.\n"
            "Se usa el horario configurado (normal o verano) segun el mes.\n"
            "Los fines de semana y dias sin bloques se saltan automaticamente."
        ), style="Surface.TLabel", font=F["body"],
            foreground=C["text_sec"]).pack(anchor="w", pady=(0, 16))

        range_frame = tk.Frame(pad, bg=C["surface"])
        range_frame.pack(fill=X, pady=(0, 16))

        ttk.Label(range_frame, text="Desde", style="Surface.TLabel",
                  font=F["label"], foreground=C["text_sec"]).pack(anchor="w")
        today_str = date.today().strftime("%Y-%m-%d")
        self._bulk_start = StringVar(value=today_str)
        DateEntry(range_frame, self._bulk_start, C, F, width=14).pack(
            anchor="w", pady=(4, 12))

        ttk.Label(range_frame, text="Hasta", style="Surface.TLabel",
                  font=F["label"], foreground=C["text_sec"]).pack(anchor="w")
        self._bulk_end = StringVar(value=today_str)
        DateEntry(range_frame, self._bulk_end, C, F, width=14).pack(
            anchor="w", pady=(4, 0))

        ttk.Label(pad, text="Excluir fechas",
                  style="Surface.TLabel", font=F["label"],
                  foreground=C["text_sec"]).pack(anchor="w", pady=(0, 4))
        self._bulk_exclude = StringVar(value="")
        ModernEntry(pad, C, F, textvariable=self._bulk_exclude,
                    width=40).pack(anchor="w")
        ttk.Label(pad, text="Fechas en formato YYYY-MM-DD, separadas por comas",
                  style="Surface.TLabel", font=F["helper"],
                  foreground=C["text_dis"]).pack(anchor="w", pady=(2, 16))

        ttk.Label(pad, text="Vista previa",
                  style="Surface.TLabel", font=F["body_b"],
                  foreground=C["text"]).pack(anchor="w", pady=(8, 4))
        self._bulk_preview = tk.Text(
            pad, height=10, font=F["mono"],
            bg=C["code_bg"], fg=C["code_text"], relief="flat",
            borderwidth=0, padx=12, pady=10, state="disabled",
            highlightthickness=1, highlightbackground=C["border"],
            highlightcolor=C["border"])
        self._bulk_preview.pack(fill=BOTH, expand=True, pady=(0, 12))

        btn_frame = tk.Frame(pad, bg=C["surface"])
        btn_frame.pack(fill=X)
        ModernButton(btn_frame, "Previsualizar", C, F,
                     command=self._bulk_preview_days, padx=14, pady=6).pack(
            side=LEFT, padx=(0, 8))
        ModernButton(btn_frame, "Fichar rango", C, F, variant="primary",
                     command=self._fichar_bulk).pack(side=LEFT)

    def _bulk_preview_days(self) -> None:
        from datetime import timedelta
        try:
            start = dt.strptime(self._bulk_start.get().strip(), "%Y-%m-%d").date()
            end = dt.strptime(self._bulk_end.get().strip(), "%Y-%m-%d").date()
        except ValueError:
            messagebox.showerror("Error", "Formato de fecha invalido. Usa YYYY-MM-DD.")
            return
        if start > end:
            messagebox.showerror("Error", "La fecha de inicio no puede ser posterior a la de fin.")
            return

        excluded_dates = set()
        raw_exc = self._bulk_exclude.get().strip()
        if raw_exc:
            for part in raw_exc.split(","):
                part = part.strip()
                if part:
                    try:
                        excluded_dates.add(dt.strptime(part, "%Y-%m-%d").date())
                    except ValueError:
                        messagebox.showerror("Error", f"Fecha invalida: {part}")
                        return

        skip = set(self.cfg.get("behavior", {}).get("skip_weekdays", []))
        lines = []
        count = 0
        excluded_count = 0
        current = start
        while current <= end:
            if current in excluded_dates:
                lines.append(f"  {current} ({WEEKDAYS_FULL[current.weekday()]:9s})  EXCLUIDO")
                excluded_count += 1
            elif current.weekday() not in skip:
                try:
                    import odoo_attendance as _m
                    blocks = _m.get_today_blocks(current, self.cfg)
                except Exception:
                    blocks = []
                if blocks:
                    bs = ", ".join(f"{b[0]}-{b[1]} [{b[2]}]" for b in blocks)
                    lines.append(f"  {current} ({WEEKDAYS_FULL[current.weekday()]:9s})  {bs}")
                    count += 1
                else:
                    lines.append(f"  {current} ({WEEKDAYS_FULL[current.weekday()]:9s})  (sin bloques)")
            current += timedelta(days=1)

        header = f"Dias a fichar: {count}"
        if excluded_count:
            header += f"    Excluidos: {excluded_count}"
        header += f"    Rango: {start} -> {end}\n"
        header += "-" * 60 + "\n"
        self._bulk_preview.configure(state="normal")
        self._bulk_preview.delete("1.0", END)
        self._bulk_preview.insert("1.0", header + "\n".join(lines))
        self._bulk_preview.configure(state="disabled")

    def _fichar_bulk(self) -> None:
        C, F = self.C, self.F
        if self._dirty:
            if not messagebox.askyesno("Cambios sin guardar",
                "Hay cambios sin guardar. Guardar antes de fichar?"):
                return
            self._save()

        try:
            start = dt.strptime(self._bulk_start.get().strip(), "%Y-%m-%d").date()
            end = dt.strptime(self._bulk_end.get().strip(), "%Y-%m-%d").date()
        except ValueError:
            messagebox.showerror("Error", "Formato de fecha invalido.")
            return
        if start > end:
            messagebox.showerror("Error", "La fecha de inicio no puede ser posterior a la de fin.")
            return

        excluded_dates = []
        excluded_str = self._bulk_exclude.get().strip()
        if excluded_str:
            for part in excluded_str.split(","):
                part = part.strip()
                if part:
                    try:
                        excluded_dates.append(dt.strptime(part, "%Y-%m-%d").date())
                    except ValueError:
                        messagebox.showerror("Error", f"Fecha invalida: {part}")
                        return

        excluded_msg = ""
        if excluded_dates:
            excluded_msg = "\nExcluyendo: " + ", ".join(
                d.strftime("%Y-%m-%d") for d in excluded_dates)

        if not messagebox.askyesno("Fichaje en masa",
            f"Se va a fichar el rango {start} a {end}.{excluded_msg}\n\n"
            "Se registrara la asistencia via API.\n\nContinuar?"):
            return

        if not ATTENDANCE_SCRIPT.exists():
            messagebox.showerror("Error", f"No se encuentra {ATTENDANCE_SCRIPT}")
            return

        win = tk.Toplevel(self.root)
        win.title("Fichaje en masa")
        win.geometry("620x420")
        win.transient(self.root)
        win.configure(bg=C["surface"])
        txt = scrolledtext.ScrolledText(
            win, width=72, height=20, font=F["mono"],
            bg=C["code_bg"], fg=C["code_text"], relief="flat", borderwidth=0,
            padx=12, pady=12)
        txt.pack(fill=BOTH, expand=True)
        txt.insert(END, f"Fichando rango {start} a {end}...\n\n")
        txt.configure(state="disabled")

        def run() -> None:
            try:
                cmd = [str(PYTHON_EXE), str(ATTENDANCE_SCRIPT), "--bulk",
                       start.strftime("%Y-%m-%d"), end.strftime("%Y-%m-%d")]
                if excluded_dates:
                    cmd.append("--exclude")
                    cmd.append(",".join(d.strftime("%Y-%m-%d") for d in excluded_dates))
                proc = subprocess.run(
                    cmd, cwd=str(SCRIPT_DIR),
                    capture_output=True, text=True, timeout=1800,
                    startupinfo=_no_console_si())
                msg = (proc.stdout or "") + (
                    "\n--- stderr ---\n" + proc.stderr if proc.stderr else "")
                msg += f"\n[exit code {proc.returncode}]"
            except subprocess.TimeoutExpired:
                msg = "TIMEOUT."
            except Exception as exc:
                msg = f"ERROR: {exc}"
            txt.configure(state="normal")
            txt.insert(END, msg + "\n")
            txt.configure(state="disabled")
            txt.see(END)

        threading.Thread(target=run, daemon=True).start()

    # ── Actions ───────────────────────────────────────────────────────────
    def _mark_dirty(self, *_args) -> None:
        self._dirty = True

    def _collect(self) -> dict:
        cfg = default_config()
        cfg["odoo"]["url"] = self._url.get().strip()
        cfg["odoo"]["username"] = self._user.get().strip()
        cfg["odoo"]["password"] = self._pass.get().strip()
        cfg["odoo"]["headless"] = self._headless.get()
        cfg["odoo"]["user_data_dir"] = self._udd.get().strip()
        cfg["behavior"]["enabled"] = self._enabled.get()
        cfg["behavior"]["skip_weekdays"] = [
            i for i, v in enumerate(self._skip_vars) if v.get()
        ]
        sm_raw = [m.strip() for m in self._summer_months.get().split(",") if m.strip()]
        try:
            cfg["schedule"]["summer_months"] = [int(m) for m in sm_raw]
        except ValueError:
            cfg["schedule"]["summer_months"] = []
        for kind in ("normal", "summer"):
            cfg["schedule"][kind] = {
                str(i): self._day_editors[kind][str(i)].get_blocks()
                for i in range(7)
            }
        cfg["schedule"]["special_days"] = {
            k: ed.get_blocks() for k, ed in self._special_editors.items()
        }
        return cfg

    def _save(self) -> None:
        try:
            save_config(self._collect())
        except Exception as exc:
            messagebox.showerror("Error al guardar", str(exc))
            return
        self.cfg = self._collect()
        self._dirty = False
        messagebox.showinfo("Guardado", "Configuracion guardada correctamente.")

    def _fichar_ahora(self) -> None:
        C, F = self.C, self.F
        if self._dirty:
            if not messagebox.askyesno("Cambios sin guardar",
                "Hay cambios sin guardar. Guardar antes de fichar?"):
                return
            self._save()

        if not ATTENDANCE_SCRIPT.exists():
            messagebox.showerror("Error", f"No se encuentra {ATTENDANCE_SCRIPT}")
            return

        if not messagebox.askyesno("Fichar ahora",
            "Se va a registrar la asistencia de hoy.\n\nContinuar?"):
            return

        win = tk.Toplevel(self.root)
        win.title("Fichando...")
        win.geometry("540x300")
        win.transient(self.root)
        win.configure(bg=C["surface"])
        txt = scrolledtext.ScrolledText(
            win, width=60, height=14, font=F["mono"],
            bg=C["code_bg"], fg=C["code_text"], relief="flat", borderwidth=0,
            padx=12, pady=12)
        txt.pack(fill=BOTH, expand=True)
        txt.insert(END, "Ejecutando...\n")
        txt.configure(state="disabled")

        def run() -> None:
            try:
                proc = subprocess.run(
                    [str(PYTHON_EXE), str(ATTENDANCE_SCRIPT)],
                    cwd=str(SCRIPT_DIR), capture_output=True, text=True,
                    timeout=600, startupinfo=_no_console_si())
                msg = (proc.stdout or "") + (
                    "\n--- stderr ---\n" + proc.stderr if proc.stderr else "")
                msg += f"\n[exit code {proc.returncode}]"
            except subprocess.TimeoutExpired:
                msg = "TIMEOUT."
            except Exception as exc:
                msg = f"ERROR: {exc}"
            txt.configure(state="normal")
            txt.insert(END, msg + "\n")
            txt.configure(state="disabled")
            txt.see(END)

        threading.Thread(target=run, daemon=True).start()

    # ── Updates ───────────────────────────────────────────────────────────
    def _check_updates_bg(self) -> None:
        import check_updates as _cu

        def _run() -> None:
            try:
                info = _cu.check_for_updates(APP_VERSION)
            except Exception:
                return
            if not info.has_update:
                return
            self.root.after(0, lambda: self._show_update_notification(info))

        threading.Thread(target=_run, daemon=True).start()

    def _show_update_notification(self, info) -> None:
        import check_updates as _cu
        msg = (
            f"Hay una nueva version disponible.\n\n"
            f"  Instalada:  v{info.current_version}\n"
            f"  Disponible: {info.latest_version}\n\n"
            f"Descargar e instalar ahora?\n"
            f"(Tu configuracion se conservara)"
        )
        if not messagebox.askyesno("Actualizacion disponible", msg):
            return

        win = tk.Toplevel(self.root)
        win.title("Actualizando...")
        win.geometry("380x100")
        win.transient(self.root)
        win.configure(bg=self.C["surface"])
        ttk.Label(win,
            text="Descargando e instalando...\nEsto puede tardar un minuto.",
            padding=24, font=self.F["body"], anchor="center").pack(expand=True)

        def _run_update() -> None:
            ok = _cu.download_and_apply_update(info.installer_url)
            self.root.after(0, lambda: self._update_done(win, ok))

        threading.Thread(target=_run_update, daemon=True).start()

    def _update_done(self, win, ok: bool) -> None:
        win.destroy()
        if ok:
            messagebox.showinfo("Actualizacion completada",
                "La aplicacion se ha actualizado correctamente.\n"
                "Reinicia la aplicacion para usar la nueva version.")
        else:
            messagebox.showerror("Error",
                "No se pudo completar la actualizacion.")

    def _on_close(self) -> None:
        if self._dirty:
            if not messagebox.askyesno("Salir",
                "Hay cambios sin guardar. Salir de todos modos?"):
                return
        self.root.destroy()

    def run(self) -> None:
        self.root.mainloop()


def main() -> int:
    ConfigApp().run()
    return 0


if __name__ == "__main__":
    sys.exit(main())
