"""Configuration GUI for the Odoo Attendance automation.

A standalone tkinter app to edit config.toml visually:
  - Odoo credentials & browser options
  - Master enable/disable switch
  - Skip weekdays
  - Summer months
  - Normal schedule (per weekday, editable blocks)
  - Summer/intensive schedule (per weekday, editable blocks)
  - Special days (MM-DD)
  - "Fichar ahora" button: runs the attendance automation immediately,
    ignoring today's marker (useful if you dismissed the dialog by mistake).

Launchers: configurar.bat (Windows) / configurar.sh (Linux).
"""

from __future__ import annotations

import os
import subprocess
import sys
import threading
from datetime import date
from pathlib import Path
from tkinter import (
    BOTH,
    END,
    LEFT,
    RIGHT,
    TOP,
    BOTTOM,
    X,
    Y,
    StringVar,
    BooleanVar,
    messagebox,
    scrolledtext,
    ttk,
)
import tkinter as tk

try:  # Python 3.11+
    import tomllib
except ModuleNotFoundError:  # Python 3.10
    import tomli as tomllib  # type: ignore[no-redef]

try:
    if sys.version_info >= (3, 11):
        import tomllib as _toml_w  # read only; we write manually below
    else:
        import tomli as _toml_w
except ModuleNotFoundError:
    _toml_w = None

SCRIPT_DIR = Path(__file__).resolve().parent
CONFIG_PATH = SCRIPT_DIR / "config.toml"
EXAMPLE_PATH = SCRIPT_DIR / "config.example.toml"
ATTENDANCE_SCRIPT = SCRIPT_DIR / "odoo_attendance.py"
PYTHON_EXE = Path(sys.executable)

from version import get_version
APP_VERSION = get_version()

WEEKDAYS_ES = ["Lunes", "Martes", "Mi\u00e9rcoles", "Jueves", "Viernes", "S\u00e1bado", "Domingo"]


# ---------------------------------------------------------------------------
# Config load / save
# ---------------------------------------------------------------------------
def default_config() -> dict:
    return {
        "odoo": {
            "url": "https://demo.odoo.com/odoo",
            "username": "demo@ejemplo.com",
            "password": "CAMBIAR_ESTA_CONTRASENA",
            "headless": False,
            "user_data_dir": "",
        },
        "behavior": {"enabled": True, "skip_weekdays": [5, 6], "check_updates": True},
        "schedule": {
            "summer_months": [7, 8],
            "summer": {str(i): [] for i in range(7)},
            "normal": {str(i): [] for i in range(7)},
            "special_days": {},
        },
    }


def load_config() -> dict:
    path = CONFIG_PATH if CONFIG_PATH.exists() else EXAMPLE_PATH
    if path.exists():
        with open(path, "rb") as fh:
            cfg = tomllib.load(fh)
        # Fill missing keys so the GUI always has something to show.
        base = default_config()
        base["odoo"].update(cfg.get("odoo", {}))
        base["behavior"].update(cfg.get("behavior", {}))
        sched = cfg.get("schedule", {})
        base["schedule"]["summer_months"] = sched.get("summer_months", [7, 8])
        for kind in ("summer", "normal"):
            base["schedule"][kind] = {
                str(i): [tuple(b) for b in sched.get(kind, {}).get(str(i), [])]
                for i in range(7)
            }
        base["schedule"]["special_days"] = {
            k: [tuple(b) for b in v] for k, v in sched.get("special_days", {}).items()
        }
        return base
    return default_config()


def _fmt_str(s: str) -> str:
    """Quote a TOML basic string, escaping backslashes and quotes."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def save_config(cfg: dict) -> None:
    """Write config.toml by hand (stdlib has no TOML writer)."""
    odoo = cfg["odoo"]
    beh = cfg["behavior"]
    sched = cfg["schedule"]

    def day_block_lines(blocks: list, indent: str) -> str:
        if not blocks:
            return "[]"
        inner = ", ".join(f"[{_fmt_str(b[0])}, {_fmt_str(b[1])}, {_fmt_str(b[2])}]" for b in blocks)
        return f"[{inner}]"

    lines: list[str] = []
    lines.append("# Odoo Attendance - Configuration (generated by config_gui.py)")
    lines.append("")
    lines.append("[odoo]")
    lines.append(f"url = {_fmt_str(str(odoo.get('url', '')))}")
    lines.append(f"username = {_fmt_str(str(odoo.get('username', '')))}")
    lines.append(f"password = {_fmt_str(str(odoo.get('password', '')))}")
    lines.append(f"headless = {str(bool(odoo.get('headless', False))).lower()}")
    lines.append(f"user_data_dir = {_fmt_str(str(odoo.get('user_data_dir', '')))}")
    lines.append("")
    lines.append("[behavior]")
    lines.append(f"enabled = {str(bool(beh.get('enabled', True))).lower()}")
    skip = beh.get("skip_weekdays", [])
    lines.append(f"skip_weekdays = [{', '.join(str(int(x)) for x in skip)}]")
    lines.append("")
    lines.append("[schedule]")
    sm = sched.get("summer_months", [])
    lines.append(f"summer_months = [{', '.join(str(int(x)) for x in sm)}]")
    for kind, label in (("summer", "summer / intensive"), ("normal", "normal")):
        lines.append("")
        lines.append(f"# {label} schedule  (0=Monday ... 6=Sunday)")
        lines.append(f"[schedule.{kind}]")
        for i in range(7):
            blocks = sched.get(kind, {}).get(str(i), [])
            lines.append(f"{i} = {day_block_lines(blocks, '')}")
    lines.append("")
    lines.append('# Special days  (key = "MM-DD")')
    lines.append("[schedule.special_days]")
    sd = sched.get("special_days", {})
    if sd:
        for k in sorted(sd.keys()):
            lines.append(f'{_fmt_str(k)} = {day_block_lines(sd[k], "")}')
    else:
        lines.append("# (none)")
    lines.append("")
    CONFIG_PATH.write_text("\n".join(lines), encoding="utf-8")


# ---------------------------------------------------------------------------
# Block editor widget (one weekday)
# ---------------------------------------------------------------------------
class DayEditor(ttk.Frame):
    """Editor for a single weekday: a list of [in, out, category] blocks."""

    def __init__(self, master, weekday_name: str, blocks: list, on_change):
        super().__init__(master, borderwidth=1, relief="groove", padding=6)
        self._on_change = on_change
        self._rows: list[list[tk.Widget]] = []

        header = ttk.Label(self, text=weekday_name, font=("Segoe UI", 10, "bold") if os.name == "nt" else ("Sans", 10, "bold"))
        header.pack(anchor="w")

        self._table = ttk.Frame(self)
        self._table.pack(fill=X)

        # Column headers
        for c, txt in enumerate(["Entrada", "Salida", "Categor\u00eda", ""]):
            ttk.Label(self._table, text=txt).grid(row=0, column=c, padx=4, sticky="w")

        for b in blocks:
            self._add_row(b)

        add_btn = ttk.Button(self, text="+ A\u00f1adir bloque", width=16, command=lambda: self._add_row(["09:00", "14:00", "Trabajo"]))
        add_btn.pack(anchor="w", pady=(4, 0))

    def _add_row(self, block) -> None:
        r = len(self._rows) + 1
        in_var = StringVar(value=block[0])
        out_var = StringVar(value=block[1])
        cat_var = StringVar(value=block[2])
        e1 = ttk.Entry(self._table, textvariable=in_var, width=8)
        e2 = ttk.Entry(self._table, textvariable=out_var, width=8)
        e3 = ttk.Entry(self._table, textvariable=cat_var, width=12)
        for w, var in ((e1, in_var), (e2, out_var), (e3, cat_var)):
            w.grid(row=r, column=0 if w is e1 else 1 if w is e2 else 2, padx=4, pady=2)
            var.trace_add("write", lambda *_: self._on_change())
        del_btn = ttk.Button(self._table, text="X", width=3, command=lambda: self._del_row(r))
        del_btn.grid(row=r, column=3, padx=2)
        self._rows.append([e1, e2, e3, del_btn, in_var, out_var, cat_var])

    def _del_row(self, row_idx: int) -> None:
        # row_idx is 1-based grid row; find matching entry
        for i, row in enumerate(self._rows):
            if row[3].grid_info().get("row") == row_idx:
                for w in row[:4]:
                    w.destroy()
                self._rows.pop(i)
                self._on_change()
                return

    def get_blocks(self) -> list[list[str]]:
        result = []
        for row in self._rows:
            cin = row[4].get().strip()
            cout = row[5].get().strip()
            cat = row[6].get().strip()
            if cin or cout or cat:
                result.append([cin, cout, cat])
        return result


# ---------------------------------------------------------------------------
# Main application
# ---------------------------------------------------------------------------
class ConfigApp:
    def __init__(self) -> None:
        self.cfg = load_config()
        self.root = tk.Tk()
        self.root.title(f"Odoo Attendance - Configuraci\u00f3n  v{APP_VERSION}")
        self.root.geometry("780x640")
        self.root.minsize(700, 560)
        self._dirty = False

        self._build_ui()
        self.root.protocol("WM_DELETE_WINDOW", self._on_close)

        # Check for updates in background (if enabled)
        if self.cfg.get("behavior", {}).get("check_updates", True):
            self.root.after(1000, self._check_updates_bg)

    # ---- UI ---------------------------------------------------------------
    def _build_ui(self) -> None:
        nb = ttk.Notebook(self.root)
        nb.pack(fill=BOTH, expand=True, padx=8, pady=8)

        self._tab_general = ttk.Frame(nb)
        self._tab_normal = ttk.Frame(nb)
        self._tab_summer = ttk.Frame(nb)
        self._tab_special = ttk.Frame(nb)
        self._tab_bulk = ttk.Frame(nb)
        nb.add(self._tab_general, text="General / Credenciales")
        nb.add(self._tab_normal, text="Horario normal")
        nb.add(self._tab_summer, text="Horario verano")
        nb.add(self._tab_special, text="D\u00edas especiales")
        nb.add(self._tab_bulk, text="Fichaje en masa")

        self._build_general(self._tab_general)
        self._build_schedule(self._tab_normal, "normal")
        self._build_schedule(self._tab_summer, "summer")
        self._build_special(self._tab_special)
        self._build_bulk(self._tab_bulk)

        # Bottom bar
        bar = ttk.Frame(self.root)
        bar.pack(fill=X, padx=8, pady=(0, 8))
        ttk.Button(bar, text="Fichar ahora", command=self._fichar_ahora).pack(side=LEFT)
        ttk.Button(bar, text="Guardar", command=self._save).pack(side=RIGHT)
        ttk.Button(bar, text="Cancelar", command=self._on_close).pack(side=RIGHT, padx=(0, 6))

    def _build_general(self, parent) -> None:
        odoo = self.cfg["odoo"]
        beh = self.cfg["behavior"]

        # Credentials group
        cred = ttk.LabelFrame(parent, text="Credenciales Odoo", padding=10)
        cred.pack(fill=X, padx=8, pady=8)

        self._url = StringVar(value=odoo.get("url", ""))
        self._user = StringVar(value=odoo.get("username", ""))
        self._pass = StringVar(value=odoo.get("password", ""))
        self._headless = BooleanVar(value=bool(odoo.get("headless", False)))
        self._udd = StringVar(value=odoo.get("user_data_dir", ""))

        for r, (label, var, show) in enumerate([
            ("URL Odoo", self._url, None),
            ("Usuario", self._user, None),
            ("Contrase\u00f1a", self._pass, "*"),
            ("Perfil Chrome (opcional)", self._udd, None),
        ]):
            ttk.Label(cred, text=label).grid(row=r, column=0, sticky="w", pady=4)
            entry = ttk.Entry(cred, textvariable=var, width=50, show=show or "")
            entry.grid(row=r, column=1, padx=8, pady=4, sticky="we")
            var.trace_add("write", self._mark_dirty)
        ttk.Checkbutton(cred, text="Chrome en modo headless (sin ventana visible)", variable=self._headless, command=self._mark_dirty).grid(
            row=4, column=0, columnspan=2, sticky="w", pady=4
        )
        cred.columnconfigure(1, weight=1)

        # Behavior group
        bgrp = ttk.LabelFrame(parent, text="Comportamiento", padding=10)
        bgrp.pack(fill=X, padx=8, pady=8)

        self._enabled = BooleanVar(value=bool(beh.get("enabled", True)))
        ttk.Checkbutton(
            bgrp,
            text="Activar di\u00e1logo de fichaje al desbloquear el PC",
            variable=self._enabled,
            command=self._mark_dirty,
        ).pack(anchor="w", pady=(0, 8))

        ttk.Label(bgrp, text="D\u00edas de la semana en los que NO preguntar:").pack(anchor="w")
        self._skip_vars = [BooleanVar(value=(i in beh.get("skip_weekdays", []))) for i in range(7)]
        skip_frame = ttk.Frame(bgrp)
        skip_frame.pack(anchor="w", pady=4)
        for i, name in enumerate(WEEKDAYS_ES):
            cb = ttk.Checkbutton(skip_frame, text=name, variable=self._skip_vars[i], command=self._mark_dirty)
            cb.grid(row=0, column=i, padx=4)

        # Summer months
        ttk.Label(bgrp, text="Meses con horario de verano/intensivo (1-12):").pack(anchor="w", pady=(10, 0))
        self._summer_months = StringVar(value=", ".join(str(m) for m in self.cfg["schedule"].get("summer_months", [])))
        ttk.Entry(bgrp, textvariable=self._summer_months, width=30).pack(anchor="w", pady=4)
        ttk.Label(bgrp, text="(ej: 7, 8  \u2014  vac\u00edo = sin horario de verano)", foreground="gray").pack(anchor="w")
        self._summer_months.trace_add("write", self._mark_dirty)

    def _build_schedule(self, parent, kind: str) -> None:
        canvas = tk.Canvas(parent, borderwidth=0, highlightthickness=0)
        scroll = ttk.Scrollbar(parent, orient="vertical", command=canvas.yview)
        inner = ttk.Frame(canvas)
        inner.bind(
            "<Configure>",
            lambda e: canvas.configure(scrollregion=canvas.bbox("all")),
        )
        canvas.create_window((0, 0), window=inner, anchor="nw")
        canvas.configure(yscrollcommand=scroll.set)
        canvas.pack(side=LEFT, fill=BOTH, expand=True)
        scroll.pack(side=RIGHT, fill=Y)

        self._day_editors: dict[str, dict[str, DayEditor]] = getattr(self, "_day_editors", {})
        self._day_editors[kind] = {}
        days = self.cfg["schedule"].get(kind, {})
        for i in range(7):
            blocks = days.get(str(i), [])
            ed = DayEditor(inner, WEEKDAYS_ES[i], blocks, self._mark_dirty)
            ed.pack(fill=X, padx=6, pady=4)
            self._day_editors[kind][str(i)] = ed

        # Mouse wheel scrolling
        def _wheel(event):
            canvas.yview_scroll(int(-1 * (event.delta / 120)), "units")
        canvas.bind_all("<MouseWheel>", _wheel)

    def _build_special(self, parent) -> None:
        top = ttk.Frame(parent)
        top.pack(fill=X, padx=8, pady=8)
        ttk.Label(top, text="D\u00edas especiales (formato MM-DD):").pack(side=LEFT)
        self._special_editors: dict[str, DayEditor] = {}
        self._special_container = ttk.Frame(parent)
        self._special_container.pack(fill=BOTH, expand=True, padx=8, pady=4)

        add_frame = ttk.Frame(top)
        add_frame.pack(side=LEFT, padx=(10, 0))
        self._new_sd = StringVar(value="")
        ttk.Entry(add_frame, textvariable=self._new_sd, width=8).pack(side=LEFT)
        ttk.Button(add_frame, text="+ A\u00f1adir", command=self._add_special).pack(side=LEFT, padx=4)

        for k, blocks in self.cfg["schedule"].get("special_days", {}).items():
            self._add_special_editor(k, blocks)

    def _add_special(self) -> None:
        key = self._new_sd.get().strip()
        if not key:
            return
        # normalize to MM-DD
        try:
            mm, dd = key.split("-")
            key = f"{int(mm):02d}-{int(dd):02d}"
        except ValueError:
            messagebox.showerror("Error", "Formato inv\u00e1lido. Usa MM-DD (ej: 12-24).")
            return
        if key in self._special_editors:
            return
        self._add_special_editor(key, [["08:00", "12:00", "Trabajo"]])
        self._new_sd.set("")
        self._mark_dirty()

    def _add_special_editor(self, key: str, blocks: list) -> None:
        frame = ttk.Frame(self._special_container, borderwidth=1, relief="groove", padding=4)
        frame.pack(fill=X, pady=4)
        top = ttk.Frame(frame)
        top.pack(fill=X)
        ttk.Label(top, text=f"D\u00eda {key}", font=("Segoe UI", 10, "bold") if os.name == "nt" else ("Sans", 10, "bold")).pack(side=LEFT)
        ttk.Button(top, text="Eliminar d\u00eda", width=12, command=lambda: self._del_special(key, frame)).pack(side=RIGHT)
        ed = DayEditor(frame, "", blocks, self._mark_dirty)
        ed.pack(fill=X)
        self._special_editors[key] = ed

    def _del_special(self, key: str, frame) -> None:
        frame.destroy()
        self._special_editors.pop(key, None)
        self._mark_dirty()

    # ---- Actions ----------------------------------------------------------
    def _build_bulk(self, parent) -> None:
        """Pestaña de fichaje en masa: ficha un rango de fechas de golpe."""
        from datetime import date, timedelta

        frame = ttk.LabelFrame(parent, text="Fichaje por rango de fechas", padding=16)
        frame.pack(fill=BOTH, expand=True, padx=8, pady=8)

        info = ttk.Label(
            frame,
            text=(
                "Ficha automaticamente todos los dias laborables entre dos fechas.\n"
                "Para cada dia se usara el horario configurado (normal o verano)\n"
                "segun el mes. Los fines de semana y dias sin bloques se saltan.\n\n"
                "Se abrira Chrome y fichara cada dia secuencialmente. No cierres\n"
                "la ventana hasta que termine el proceso."
            ),
            justify="left",
            padding=8,
        )
        info.pack(fill=X, pady=(0, 16))

        # Date range selectors
        range_frame = ttk.Frame(frame)
        range_frame.pack(fill=X, pady=8)

        ttk.Label(range_frame, text="Desde:").grid(row=0, column=0, padx=4, sticky="e")
        self._bulk_start = StringVar(value=date.today().strftime("%Y-%m-%d"))
        ttk.Entry(range_frame, textvariable=self._bulk_start, width=14).grid(row=0, column=1, padx=4)
        ttk.Label(range_frame, text="(YYYY-MM-DD)", foreground="gray").grid(row=0, column=2, padx=4)

        ttk.Label(range_frame, text="Hasta:").grid(row=0, column=3, padx=8, sticky="e")
        self._bulk_end = StringVar(value=date.today().strftime("%Y-%m-%d"))
        ttk.Entry(range_frame, textvariable=self._bulk_end, width=14).grid(row=0, column=4, padx=4)
        ttk.Label(range_frame, text="(YYYY-MM-DD)", foreground="gray").grid(row=0, column=5, padx=4)

        # Exceptions
        exc_frame = ttk.Frame(frame)
        exc_frame.pack(fill=X, pady=4)
        ttk.Label(exc_frame, text="Excluir fechas:").pack(side=LEFT, padx=4)
        self._bulk_exclude = StringVar(value="")
        ttk.Entry(exc_frame, textvariable=self._bulk_exclude, width=50).pack(side=LEFT, padx=4, fill=X, expand=True)
        ttk.Label(exc_frame, text="(YYYY-MM-DD separadas por comas)", foreground="gray").pack(side=LEFT, padx=4)

        # Preview of days to process
        self._bulk_preview = tk.Text(frame, height=8, font=("Consolas", 9) if os.name == "nt" else ("Mono", 9), state="disabled")
        self._bulk_preview.pack(fill=BOTH, expand=True, pady=(12, 8))

        btn_frame = ttk.Frame(frame)
        btn_frame.pack(fill=X, pady=4)
        ttk.Button(btn_frame, text="Previsualizar dias", command=self._bulk_preview_days).pack(side=LEFT, padx=4)
        ttk.Button(btn_frame, text="Fichar rango", command=self._fichar_bulk).pack(side=LEFT, padx=4)

    def _bulk_preview_days(self) -> None:
        """Show which days would be fiched without actually doing it."""
        from datetime import datetime, date, timedelta
        try:
            start = datetime.strptime(self._bulk_start.get().strip(), "%Y-%m-%d").date()
            end = datetime.strptime(self._bulk_end.get().strip(), "%Y-%m-%d").date()
        except ValueError:
            messagebox.showerror("Error", "Formato de fecha invalido. Usa YYYY-MM-DD.")
            return
        if start > end:
            messagebox.showerror("Error", "La fecha de inicio no puede ser posterior a la de fin.")
            return

        # Parse excluded dates
        excluded_dates = set()
        raw_exc = self._bulk_exclude.get().strip()
        if raw_exc:
            for part in raw_exc.split(","):
                part = part.strip()
                if part:
                    try:
                        excluded_dates.add(datetime.strptime(part, "%Y-%m-%d").date())
                    except ValueError:
                        messagebox.showerror("Error", f"Fecha de exclusion invalida: {part}")
                        return

        skip = set(self.cfg.get("behavior", {}).get("skip_weekdays", []))
        weekday_names = ["Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado", "Domingo"]
        lines = []
        count = 0
        excluded_count = 0
        current = start
        while current <= end:
            if current in excluded_dates:
                lines.append(f"  {current} ({weekday_names[current.weekday()]:9s}) -> EXCLUIDO")
                excluded_count += 1
            elif current.weekday() not in skip:
                # Import get_today_blocks from odoo_attendance
                import sys as _sys
                _sys.path.insert(0, str(SCRIPT_DIR))
                try:
                    import odoo_attendance as _m
                    blocks = _m.get_today_blocks(current, self.cfg)
                except Exception:
                    blocks = []
                if blocks:
                    blocks_str = ", ".join(f"{b[0]}-{b[1]} [{b[2]}]" for b in blocks)
                    lines.append(f"  {current} ({weekday_names[current.weekday()]:9s}) -> {blocks_str}")
                    count += 1
                else:
                    lines.append(f"  {current} ({weekday_names[current.weekday()]:9s}) -> (sin bloques)")
            current += timedelta(days=1)

        header = f"Dias a fichar: {count}"
        if excluded_count:
            header += f"  (excluidos: {excluded_count})"
        header += f"  (rango {start} a {end})\n" + "-" * 60 + "\n"
        self._bulk_preview.configure(state="normal")
        self._bulk_preview.delete("1.0", END)
        self._bulk_preview.insert("1.0", header + "\n".join(lines))
        self._bulk_preview.configure(state="disabled")

    def _fichar_bulk(self) -> None:
        """Run fichaje en masa for the selected date range."""
        from datetime import datetime, date
        if self._dirty:
            if not messagebox.askyesno("Cambios sin guardar",
                "Hay cambios sin guardar. ¿Guardar antes de fichar?"):
                return
            self._save()

        try:
            start = datetime.strptime(self._bulk_start.get().strip(), "%Y-%m-%d").date()
            end = datetime.strptime(self._bulk_end.get().strip(), "%Y-%m-%d").date()
        except ValueError:
            messagebox.showerror("Error", "Formato de fecha invalido. Usa YYYY-MM-DD.")
            return
        if start > end:
            messagebox.showerror("Error", "La fecha de inicio no puede ser posterior a la de fin.")
            return

        # Parse excluded dates for the CLI call
        excluded_str = self._bulk_exclude.get().strip()
        excluded_dates = []
        if excluded_str:
            for part in excluded_str.split(","):
                part = part.strip()
                if part:
                    try:
                        excluded_dates.append(datetime.strptime(part, "%Y-%m-%d").date())
                    except ValueError:
                        messagebox.showerror("Error", f"Fecha de exclusion invalida: {part}")
                        return

        excluded_msg = ""
        if excluded_dates:
            excluded_msg = f"\nExcluyendo: {', '.join(d.strftime('%Y-%m-%d') for d in excluded_dates)}"

        if not messagebox.askyesno(
            "Fichaje en masa",
            f"Se va a fichar el rango {start} a {end}.{excluded_msg}\n\n"
            "Esto abrira Chrome y registrara la asistencia de cada dia\n"
            "laborable secuencialmente. Puede tardar varios minutos.\n\n"
            "¿Continuar?",
        ):
            return

        if not ATTENDANCE_SCRIPT.exists():
            messagebox.showerror("Error", f"No se encuentra {ATTENDANCE_SCRIPT}")
            return

        win = tk.Toplevel(self.root)
        win.title("Fichaje en masa en progreso...")
        win.geometry("600x400")
        win.transient(self.root)
        txt = scrolledtext.ScrolledText(win, width=74, height=22,
            font=("Consolas", 9) if os.name == "nt" else ("Mono", 9))
        txt.pack(fill=BOTH, expand=True, padx=8, pady=8)
        txt.insert(END, f"Fichando rango {start} a {end}...\n\n")
        txt.configure(state="disabled")

        def run() -> None:
            try:
                cmd = [str(PYTHON_EXE), str(ATTENDANCE_SCRIPT), "--bulk",
                       start.strftime("%Y-%m-%d"), end.strftime("%Y-%m-%d")]
                if excluded_dates:
                    cmd.append("--exclude")
                    cmd.append(",".join(d.strftime("%Y-%m-%d") for d in excluded_dates))
                proc = subprocess.run(
                    cmd,
                    cwd=str(SCRIPT_DIR),
                    capture_output=True,
                    text=True,
                    timeout=1800,
                )
                msg = (proc.stdout or "") + ("\n--- stderr ---\n" + proc.stderr if proc.stderr else "")
                msg += f"\n[exit code {proc.returncode}]"
            except subprocess.TimeoutExpired:
                msg = "TIMEOUT: el script tardó demasiado."
            except Exception as exc:
                msg = f"ERROR: {exc}"
            txt.configure(state="normal")
            txt.insert(END, msg + "\n")
            txt.configure(state="disabled")
            txt.see(END)

        threading.Thread(target=run, daemon=True).start()

    def _mark_dirty(self, *_args) -> None:
        self._dirty = True

    def _collect(self) -> dict:
        cfg = default_config()
        cfg["odoo"]["url"] = self._url.get().strip()
        cfg["odoo"]["username"] = self._user.get().strip()
        cfg["odoo"]["password"] = self._pass.get().strip()
        cfg["odoo"]["headless"] = self._headless.get()
        cfg["odoo"]["user_data_dir"] = self._udd.get().strip()
        cfg["behavior"]["enabled"] = self._enabled.get()
        cfg["behavior"]["skip_weekdays"] = [i for i, v in enumerate(self._skip_vars) if v.get()]
        sm_raw = [m.strip() for m in self._summer_months.get().split(",") if m.strip()]
        try:
            cfg["schedule"]["summer_months"] = [int(m) for m in sm_raw]
        except ValueError:
            cfg["schedule"]["summer_months"] = []
        for kind in ("normal", "summer"):
            cfg["schedule"][kind] = {
                str(i): self._day_editors[kind][str(i)].get_blocks() for i in range(7)
            }
        cfg["schedule"]["special_days"] = {
            k: ed.get_blocks() for k, ed in self._special_editors.items()
        }
        return cfg

    def _save(self) -> None:
        cfg = self._collect()
        try:
            save_config(cfg)
        except Exception as exc:  # noqa: BLE001
            messagebox.showerror("Error al guardar", str(exc))
            return
        self.cfg = cfg
        self._dirty = False
        messagebox.showinfo("Guardado", f"Configuraci\u00f3n guardada en:\n{CONFIG_PATH}")

    def _fichar_ahora(self) -> None:
        """Run the attendance automation now, ignoring today's marker."""
        if self._dirty:
            if not messagebox.askyesno(
                "Cambios sin guardar",
                "Hay cambios sin guardar. \u00bfGuardar antes de fichar?",
            ):
                return
            self._save()

        if not ATTENDANCE_SCRIPT.exists():
            messagebox.showerror("Error", f"No se encuentra {ATTENDANCE_SCRIPT}")
            return

        # Confirm
        if not messagebox.askyesno(
            "Fichar ahora",
            "Se va a ejecutar la automatizaci\u00f3n de fichaje ahora mismo.\n\n"
            "Esto abrir\u00e1 Chrome y registrar\u00e1 la asistencia de hoy\n"
            "seg\u00fan el horario configurado.\n\n\u00bfContinuar?",
        ):
            return

        win = tk.Toplevel(self.root)
        win.title("Fichando...")
        win.geometry("520x300")
        win.transient(self.root)
        txt = scrolledtext.ScrolledText(win, width=64, height=16, font=("Consolas", 9) if os.name == "nt" else ("Mono", 9))
        txt.pack(fill=BOTH, expand=True, padx=8, pady=8)
        txt.insert(END, "Ejecutando odoo_attendance.py...\n")
        txt.configure(state="disabled")

        def run() -> None:
            try:
                proc = subprocess.run(
                    [str(PYTHON_EXE), str(ATTENDANCE_SCRIPT)],
                    cwd=str(SCRIPT_DIR),
                    capture_output=True,
                    text=True,
                    timeout=600,
                )
                out = proc.stdout or ""
                err = proc.stderr or ""
                msg = out + ("\n--- stderr ---\n" + err if err else "") + f"\n[exit code {proc.returncode}]"
            except subprocess.TimeoutExpired:
                msg = "TIMEOUT: el script tard\u00f3 demasiado."
            except Exception as exc:  # noqa: BLE001
                msg = f"ERROR: {exc}"
            txt.configure(state="normal")
            txt.insert(END, msg + "\n")
            txt.configure(state="disabled")
            txt.see(END)

        threading.Thread(target=run, daemon=True).start()

    def _check_updates_bg(self) -> None:
        """Check for updates in a background thread and notify if available."""
        import check_updates as _cu

        def _run() -> None:
            try:
                info = _cu.check_for_updates(APP_VERSION)
            except Exception:
                return
            if not info.has_update:
                return
            # Schedule UI update on the main thread
            self.root.after(0, lambda: self._show_update_notification(info))

        threading.Thread(target=_run, daemon=True).start()

    def _show_update_notification(self, info) -> None:
        """Show a dialog when a new version is available."""
        import webbrowser

        msg = (
            f"Hay una nueva version disponible!\n\n"
            f"  Instalada: v{info.current_version}\n"
            f"  Disponible: {info.latest_version}\n\n"
            f"Deseas ir a la pagina de descarga?"
        )
        if messagebox.askyesno("Actualizacion disponible", msg):
            webbrowser.open(info.download_url)

    def _on_close(self) -> None:
        if self._dirty:
            if not messagebox.askyesno("Salir", "Hay cambios sin guardar. \u00bfSalir de todos modos?"):
                return
        self.root.destroy()

    def run(self) -> None:
        self.root.mainloop()


def main() -> int:
    ConfigApp().run()
    return 0


if __name__ == "__main__":
    sys.exit(main())
